[package]
name = "eb90"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7"
crc = "2"

[dev-dependencies]
proptest = "1"

[features]
default = ["alloc"]
alloc = []
